Update all examples
So they are up to date with deps and they are all working (for sure: I've tested them one by one)

Upgrade `"serverless-webpack": "file:../..",` to `"serverless-webpack": "^5.3",` because each test resulted in `Error: Cannot find module 'webpack'` ... (only with NPM not with Yarn)

- remove outdated `babel` example because it use webpack 3 and it's superseded by `babel-webpack-4`
- remove `serverless-offline` example as other one already use serverless-offline
- update all examples to latest deps version